export const IPFS_GATEWAY_HOST = 'ipfs.io';
export const IPFS_GATEWAY_PORT = 80;
export const JSON_MEDIA_TYPE = 'application/json';
export const BASE64_ENCODING = 'base64';
export const DATA_URL_PREFIX = 'data:';
export const LIMIT_VALUE_IN_BYTES = 16000000;
export const HTTP_READER_MIN_TIMEOUT = 1000;
export const HTTP_READER_MAX_TIMEOUT = 360 * 1000; // 6 minutes;
export const METADATA_REPO_PROVIDER = 'METADATA_REPO_PROVIDER';
