{
 "title": "NFT contract reader metrics",
 "description": "Application metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "NFT Contract reader gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time to fetch token URI ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "fetch_uri_gauge{instance=\"nft-contract-reader:8082\"}"
    }
   ]
  },
  {
   "title": "Tasks gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tasks_gauge{instance=\"nft-contract-reader:8082\"}"
    }
   ]
  },
  { "title": "NFT Contract reader contracts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total contract counter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_contract_counter{instance=\"nft-contract-reader:8082\"}"
    }
   ]
  },
  {
   "title": "Fetch contract name gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fetch_contract_name_gauge{instance=\"nft-contract-reader:8082\"}"
    }
   ]
  },
  {
   "title": "Update contract gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "update_contract_gauge{instance=\"nft-contract-reader:8082\"}"
    }
   ]
  },
  {
   "title": "Update contract counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "update_contract_counter{instance=\"nft-contract-reader:8082\"}"
    }
   ]
  },
  {
   "title": "Update token gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "update_token_gauge{instance=\"nft-contract-reader:8082\"}"
    }
   ]
  },
  { "title": "NFT Contract reader tokens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Update erc721 token counter",
   "type": "graph",
   "description": "erc721_token",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "update_erc721_token_counter{instance=\"nft-contract-reader:8082\"}"
    }
   ]
  },
  {
   "title": "Update erc1155 token counter",
   "type": "graph",
   "description": "erc1155_token",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "update_erc1155_token_counter{instance=\"nft-contract-reader:8082\"}"
    }
   ]
  },
  { "title": "NFT Contract reader memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(x_node_process_resident_memory_bytes{instance=\"nft-contract-reader:8082\"}) by (route)"
    }
   ]
  },
  { "title": "NFT Contract reader CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(irate(x_node_process_cpu_seconds_total{job=\"nft-explorer\", instance=\"nft-contract-reader:8082\", mode!=\"idle\"}[1m])) * 100"
    }
   ]
  }
 ]
}