{
 "title": "NFT Metadata reader metrics",
 "description": "Application metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "NFT Metadata Reader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tasks gauge",
   "type": "graph",
   "description": "NFT metadata reader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tasks_gauge{instance=\"nft-metadata-reader:8083\"}"
    }
   ]
  },
  {
   "title": "Time to get tokens",
   "type": "graph",
   "description": "NFT metadata reader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "get_tokens_gauge{instance=\"nft-metadata-reader:8083\"}"
    }
   ]
  },
  {
   "title": "Tokens counter",
   "type": "graph",
   "description": "NFT metadata reader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "token_counter{instance=\"nft-metadata-reader:8083\"}"
    }
   ]
  },
  {
   "title": "Number of retrieved tokens",
   "type": "graph",
   "description": "NFT metadata reader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tokens_gauge{instance=\"nft-metadata-reader:8083\"}"
    }
   ]
  },
  {
   "title": "Metadata counter",
   "type": "graph",
   "description": "NFT metadata reader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "metadata_counter" }
   ]
  },
  {
   "title": " Time to extract metadata from IPFS",
   "type": "graph",
   "description": "NFT metadata reader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ipfs_metadata_gauge{instance=\"nft-metadata-reader:8083\"}"
    }
   ]
  },
  {
   "title": " Time to extract metadata by HTTP",
   "type": "graph",
   "description": "NFT metadata reader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_metadata_gauge{instance=\"nft-metadata-reader:8083\"}"
    }
   ]
  },
  {
   "title": "TIme to process on-chain metadata",
   "type": "graph",
   "description": "NFT metadata reader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "on_chain_metadata_gauge{instance=\"nft-metadata-reader:8083\"}"
    }
   ]
  },
  {
   "title": "Processed IPFS metadata",
   "type": "graph",
   "description": "NFT metadata reader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ipfs_metadata_count{instance=\"nft-metadata-reader:8083\"}"
    }
   ]
  },
  {
   "title": "Processed HTTP metadata",
   "type": "graph",
   "description": "NFT metadata reader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_metadata_count{instance=\"nft-metadata-reader:8083\"}"
    }
   ]
  },
  {
   "title": "Processed on-chain metadata",
   "type": "graph",
   "description": "NFT metadata reader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "on_chain_metadata_count{instance=\"nft-metadata-reader:8083\"}"
    }
   ]
  },
  {
   "title": "Time to store metadata to DB",
   "type": "graph",
   "description": "NFT metadata reader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "store_metadata_gauge{instance=\"nft-metadata-reader:8083\"}"
    }
   ]
  },
  {
   "title": "Time of one read cycle",
   "type": "graph",
   "description": "NFT metadata reader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "processed_metadata_gauge{instance=\"nft-metadata-reader:8083\"}"
    }
   ]
  },
  {
   "title": "NFT Metadata reader memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 }
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(x_node_process_resident_memory_bytes{instance=\"nft-metadata-reader:8083\"}) by (route)"
    }
   ]
  },
  { "title": "NFT Metadata reader CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(irate(x_node_process_cpu_seconds_total{job=\"nft-explorer\", instance=\"nft-metadata-reader:8083\", mode!=\"idle\"}[1m])) * 100"
    }
   ]
  }
 ]
}