{
 "title": "NFT event reader metrics",
 "description": "Application metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "NFT Events reader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processed blocks",
   "type": "graph",
   "description": "NFT Events reader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_blocks_gauge{instance=\"nft-events-reader:8080\"}"
    }
   ]
  },
  {
   "title": "Processed events",
   "type": "graph",
   "description": "NFT Events reader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "events_counter_gauge{instance=\"nft-events-reader:8080\"}"
    }
   ]
  },
  {
   "title": "Processed events per iteration",
   "type": "graph",
   "description": "NFT Events reader",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "events_gauge{instance=\"nft-events-reader:8080\"}"
    }
   ]
  },
  {
   "title": "Time to fetch events batch",
   "type": "graph",
   "description": "NFT Events reader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "fetch_events_gauge{instance=\"nft-events-reader:8080\"}"
    }
   ]
  },
  {
   "title": "Time to save events batch",
   "type": "graph",
   "description": "NFT Events reader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "save_events_gauge{instance=\"nft-events-reader:8080\"}"
    }
   ]
  },
  {
   "title": "Time to process events batch",
   "type": "graph",
   "description": "NFT Events reader",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "total_events_gauge{instance=\"nft-events-reader:8080\"}"
    }
   ]
  },
  { "title": "NFT Events reader memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(x_node_process_resident_memory_bytes{instance=\"nft-events-reader:8080\"}) by (route)"
    }
   ]
  },
  { "title": "NFT Events reader CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(irate(x_node_process_cpu_seconds_total{job=\"nft-explorer\", instance=\"nft-events-reader:8080\", mode!=\"idle\"}[1m])) * 100"
    }
   ]
  }
 ]
}