{
 "title": "NFT Pre Contracts Indexing",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "main data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "update_pre_event_counter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "update_pre_event_counter{instance=\"nft-pre-contracts:8084\"}"
    }
   ]
  },
  {
   "title": "update_pre_contract_counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "update_pre_contract_counter{instance=\"nft-pre-contracts:8084\"}"
    }
   ]
  },
  {
   "title": "update_pre_token_counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "update_pre_token_counter{instance=\"nft-pre-contracts:8084\"}"
    }
   ]
  }
 ]
}