{
 "title": "NFT indexer metrics",
 "description": "Application metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "NFT Indexer gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fetched tokens URI per block batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tokens_fetched_uri_gauge{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Time to fetch token URI ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "fetch_uri_gauge{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Tasks gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tasks_gauge{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  { "title": "NFT Indexer blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Processed blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "block_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Time to process blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "processed_block_gauge{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  { "title": "NFT Indexer events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Processed events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "event_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "erc721_event",
   "type": "graph",
   "description": "erc721_event",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erc721_event_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "erc1155_event",
   "type": "graph",
   "description": "erc1155_event",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erc1155_event_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Events fetched per block batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "events_gauge{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Time to fetch events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "fetch_events_gauge{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  { "title": "NFT Indexer contracts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Total contract counter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_contract_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "erc1155_contract",
   "type": "graph",
   "description": "erc1155_contract",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erc1155_contract_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "erc721_contract",
   "type": "graph",
   "description": "erc721_contract",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erc721_contract_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Number of stored contracts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stored_contract_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Fetch contract name gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fetch_contract_name_gauge{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Time to store contracts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "store_contract_gauge{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Contracts fetched name gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  { "title": "NFT Indexer tokens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "erc721_token",
   "type": "graph",
   "description": "erc721_token",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erc721_token_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "erc1155_token",
   "type": "graph",
   "description": "erc1155_token",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erc1155_token_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Stored erc721 token",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stored_erc721_token_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Stored erc1155 token",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stored_erc1155_token_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Duplicate erc721 token",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "duplicate_erc721_token_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Duplicate erc1155 token",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "duplicate_erc1155_token_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Stored tokens",
   "type": "graph",
   "description": "stored_token",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stored_erc1155_token_counter{instance=\"nft-indexer:8081\"}+stored_erc721_token_counter{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Processed tokens per block batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tokens_gauge{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  {
   "title": "Time to store token",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "store_token_gauge{instance=\"nft-indexer:8081\"}"
    }
   ]
  },
  { "title": "NFT Indexer memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(x_node_process_resident_memory_bytes{instance=\"nft-indexer:8081\"}) by (route)"
    }
   ]
  },
  { "title": "NFT Indexer CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(irate(x_node_process_cpu_seconds_total{job=\"nft-explorer\", instance=\"nft-indexer:8081\", mode!=\"idle\"}[1m])) * 100"
    }
   ]
  }
 ]
}