{{- with .Values.externalSecrets }}
{{- range $k, $v := . }}
{{- if or (hasKey $v "data") (hasKey $v "dataFrom") }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $k }}
  namespace: {{ $.Release.Namespace }}
spec:
  backendType: secretsManager
  {{- if $v.data }}
  data:
    {{- toYaml $v.data | nindent 4 }}
  {{- end }}
  {{- if $v.dataFrom }}
  dataFrom:
    {{- toYaml $v.dataFrom | nindent 4 }}
  {{- end }}
  {{- if $v.template }}
  template:
    {{- toYaml $v.template | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
