{{- range $name, $deployment := .Values.deployments }}
{{- with $deployment.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nft-indexer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{- printf "%s-%s" (include "nft-indexer.name" .) $name }}
    {{- include "nft-indexer.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nft-indexer.fullname" . }}
  minReplicas: {{ $deployment.autoscaling.minReplicas }}
  maxReplicas: {{ $deployment.autoscaling.maxReplicas }}
  metrics:
    {{- if $deployment.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ $deployment.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $deployment.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ $deployment.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
