{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nft-indexer.fullname" . }}-{{ .Values.rbac.name }}
  labels:
    {{- include "nft-indexer.labels" . | nindent 4 }}
rules:
{{ .Values.rbac.rules | toYaml }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nft-indexer.fullname" . }}-{{ .Values.rbac.name }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nft-indexer.fullname" . }}-{{ .Values.rbac.name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nft-indexer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace}}
{{- end }}
