export const RABBIT_BLOCK_READ_QUEUE = 'RABBIT_BLOCK_READ_QUEUE';
export const RABBIT_CONTRACT_READ_QUEUE = 'RABBIT_CONTRACT_READ_QUEUE';
export const RABBIT_METADATA_READ_QUEUE = 'RABBIT_METADATA_READ_QUEUE';
export const SQS_BLOCKS_QUEUE = 'SQS_BLOCKS_QUEUE';
export const SQS_CONTRACTS_QUEUE = 'SQS_CONTRACTS_QUEUE';
export const SQS_METADATA_QUEUE = 'SQS_METADATA_QUEUE';
